import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const { briefId, userId, email, title, content } = await req.json()

    if (!briefId || !email) {
      return new Response(
        JSON.stringify({ error: 'Missing required fields' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Build email HTML
    const sections = []
    if (content.executiveSummary?.length) {
      sections.push(`<h2>Executive Summary</h2><ul>${content.executiveSummary.map((item: string) => `<li>${item}</li>`).join('')}</ul>`)
    }
    if (content.competitorActivity?.length) {
      sections.push(`<h2>Competitor Activity</h2><ul>${content.competitorActivity.map((item: string) => `<li>${item}</li>`).join('')}</ul>`)
    }
    if (content.industryTrends?.length) {
      sections.push(`<h2>Industry Trends</h2><ul>${content.industryTrends.map((item: string) => `<li>${item}</li>`).join('')}</ul>`)
    }
    if (content.keyInsights?.length) {
      sections.push(`<h2>Key Insights</h2><ul>${content.keyInsights.map((item: string) => `<li>${item}</li>`).join('')}</ul>`)
    }
    if (content.recommendedActions?.length) {
      sections.push(`<h2>Recommended Actions</h2><ul>${content.recommendedActions.map((item: string) => `<li>${item}</li>`).join('')}</ul>`)
    }

    const emailHtml = `
      <div style="font-family: system-ui, -apple-system, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background: linear-gradient(135deg, #FF006E, #FF4D9E); padding: 30px; border-radius: 12px; text-align: center; margin-bottom: 30px;">
          <h1 style="color: white; margin: 0; font-size: 24px;">${title}</h1>
          <p style="color: rgba(255,255,255,0.9); margin: 10px 0 0 0;">Your Weekly Intelligence Brief</p>
        </div>
        
        <div style="background: #fafafa; padding: 30px; border-radius: 8px;">
          ${sections.join('<hr style="border: none; border-top: 1px solid #e5e5e5; margin: 30px 0;">')}
        </div>
        
        <div style="text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e5e5;">
          <p style="color: #666; font-size: 14px;">Generated by Sarah, your AI Market Intelligence Analyst</p>
          <p style="color: #666; font-size: 12px; margin-top: 10px;">Pink Beam — AI Employees for Your Business</p>
        </div>
      </div>
    `

    // Send via Resend
    const resendResponse = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${Deno.env.get('RESEND_API_KEY')}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: 'Sarah at Pink Beam <onboarding@resend.dev>',
        to: [email],
        subject: title || 'Your Research Brief from Sarah',
        html: emailHtml,
      }),
    })

    if (!resendResponse.ok) {
      const error = await resendResponse.text()
      console.error('Resend error:', error)
      return new Response(
        JSON.stringify({ error: 'Failed to send email', details: error }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    return new Response(
      JSON.stringify({ success: true }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )

  } catch (error) {
    console.error('Error:', error)
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  }
})