'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Loader2 } from 'lucide-react'
import Link from 'next/link'

interface Brief {
  id: string
  title: string
  created_at: string
  status: 'draft' | 'sent'
}

export default function BriefsPage() {
  const router = useRouter()
  const [briefs, setBriefs] = useState<Brief[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    loadBriefs()
  }, [])

  const loadBriefs = async () => {
    const supabase = createClient()
    const { data: { user } } = await supabase.auth.getUser()
    
    if (!user) {
      router.push('/sign-in')
      return
    }

    const { data } = await supabase
      .from('briefs')
      .select('id, title, created_at, status')
      .eq('user_id', user.id)
      .order('created_at', { ascending: false })

    setBriefs(data || [])
    setLoading(false)
  }

  if (loading) {
    return (
      <div className="flex min-h-[calc(100vh-4rem)] items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    )
  }

  return (
    <div className="container mx-auto px-4 py-8">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl font-bold mb-2">Research Briefs</h1>
        <p className="text-muted-foreground mb-8">
          Intelligence briefs generated by Sarah
        </p>

        {briefs.length === 0 ? (
          <Card>
            <CardContent className="py-12 text-center">
              <p className="text-muted-foreground">No briefs yet.</p>
              <p className="text-sm text-muted-foreground mt-2">
                Go to <Link href="/dashboard/sarah" className="text-primary hover:underline">Sarah</Link> to generate your first brief.
              </p>
            </CardContent>
          </Card>
        ) : (
          <div className="space-y-4">
            {briefs.map((brief) => (
              <Link key={brief.id} href={`/dashboard/briefs/${brief.id}`}>
                <Card className="hover:bg-muted/50 transition-colors">
                  <CardContent className="flex items-center justify-between py-4">
                    <div>
                      <h3 className="font-semibold">{brief.title}</h3>
                      <p className="text-sm text-muted-foreground">
                        {new Date(brief.created_at).toLocaleDateString()}
                      </p>
                    </div>
                    <Badge variant={brief.status === 'sent' ? 'default' : 'secondary'}>
                      {brief.status}
                    </Badge>
                  </CardContent>
                </Card>
              </Link>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}